[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0.69"
cxx = { version = "1.0", features = ["c++20"] }
futures = "0.3.26"
wasmtime = "5.0.0"
wasmtime-wasi = "5.0.0"

[build-dependencies]
cxx-build = "1.0"
